apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-local-pv
  labels:
    project: redis-lab
spec:
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-redis
  local:
    path: /mnt/mydisk/redis-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8s-node2