# Binds the redisinsight-reader Role to the redisinsight-sa
# ServiceAccount. Permissions take effect immediately upon binding.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: redisinsight-reader-binding
  namespace: my-app-space
  labels:
    project: my-redis-k8s-lab
subjects:
- kind: ServiceAccount
  name: redisinsight-sa
roleRef:
  kind: Role
  name: redisinsight-reader
  apiGroup: rbac.authorization.k8s.io